---
dist: xenial

language: python
python: "2.7"

phpenv: 7.2

sudo: required

services:
  - docker

install:
  - pip install -r test-requirements.txt

script:
  - sonar-scanner
  - molecule test --all

addons:
  sonarcloud:
    organization: "gurkalov-github"
    token:
      secure: $SONAR_TOKEN
