---
# tasks file for lumen_deploy
- include: struct.yml
  become: true
  tags: setup

- include: dependency.yml
  become: true
  tags: setup

- include: build.yml
  tags:
    - setup
    - deploy
    - build

- include: deploy.yml
  ansible_user: "{{ app_user }}"
  tags:
    - setup
    - deploy

- include: migrate.yml
  tags:
    - setup
    - migrate

- include: start.yml
  become: true
  tags: setup
