---
- name: Deploy sandbox
  file:
    src: "{{ app_directory }}/{{ item.src }}"
    dest: "{{ app_directory }}/{{ item.dest }}"
    state: link
    force: true
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755
  with_items:
    - {src: 'releases/{{ build }}', dest: 'sandbox'}

- name: Check static version sandbox
  uri:
    url: "{{ app_sandbox_host }}/version.txt"
    return_content: true
  register: sandbox_static_version

- name: Fail if not static check
  fail:
  when: build != sandbox_static_version.content

- name: Check application version sandbox
  uri:
    url: "{{ app_sandbox_host }}/api/v1/version"
    return_content: true
  register: sandbox_application_version

- name: Fail if not application check
  fail:
  when: build != sandbox_application_version.content
