---
- name: Create app dir
  file:
    path: "{{ app_directory }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755

- name: Create app dirs
  file:
    path: "{{ app_directory }}/{{ item }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755
  with_items:
    - shared
    - releases

- name: Create shared dirs
  file:
    path: "{{ app_directory }}/shared/{{ item }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0777
  with_items:
    - storage
    - storage/app
    - storage/framework
    - storage/framework/cache
    - storage/framework/sessions
    - storage/framework/views
    - storage/logs
