---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible
  options:
    diff: true
    v: true
  lint:
    name: ansible-lint
    enabled: false
    exclude_paths:
      - ./default/src/

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    v: true
  lint:
    name: flake8
